services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=12345678Aa
    ports:
      - "1433:1433"
    volumes:
      - ./sqldata:/var/opt/mssql/data

    container_name: sqlserver